# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "megatest"
  gem "rails"
  gem "rake"
  gem "sqlite3"
  gem "standard"
  gem "standard-performance"
end
