
name: "DCO Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

env:
  STATEMENT: "I certify my contributions under the Developer Certificate of Origin in dco.txt."

jobs:
  DCOAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "DCO Assistant"
        if: github.event.comment.body == 'DCOAssistant' || github.event.comment.body == ${{ env.STATEMENT }} || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          remote-organization-name: "recheckdev"
          remote-repository-name: "dco-signatures"
          branch: 'main' # cannot be a protected branch
          path-to-signatures: "recheckdev/recheck/dco_v1.1.json" # path mirrors the org + repo
          allowlist: []
          path-to-document: "/dco.txt" # copy of https://developercertificate.org/
          create-file-commit-message: "Creating file for storing DCO certifications"
          signed-commit-message: "DCO 1.1 certified by $contributorName in PR $pullRequestNo"
          custom-notsigned-prcomment: "Hi, this is the DCO Assistant bot. Please read the [Developer Certificate of Origin](https://developercertificate.org) (also available in this repo at /dco.txt) and post a comment with exactly the text below to affirm that you have the right to submit code under the project license. You only have to do this once, and your code will not be merged wtihout it. ([More info](https://osr.finos.org/docs/bok/artifacts/clas-and-dcos))"
          custom-pr-sign-comment: ${{ env.STATEMENT }}
          custom-allsigned-prcomment: "All contributors have certified the DCO."
          lock-pullrequest-aftermerge: false
          use-dco-flag: true

